### ISSUE TITLE
Stiebel ISG instance crashed periodically on Raspi

### ISSUE THREAD

**Issue by tommi296** [unltdnetworx/ioBroker.stiebel-isg#37]
Hello,

since 2 days the Siebel ISG adapter crashes periodically. Log:

2021-03-03 20:19:50.457  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-03-03 20:19:50.459  - error: stiebel-isg.0 (23999) unhandled promise rejection: Cannot read property 'replace' of undefined
2021-03-03 20:19:50.461  - error: stiebel-isg.0 (23999) TypeError: Cannot read property 'replace' of undefined
at createISGCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:346:14)
at Node. (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:514:21)
at initialize.exports.each (/opt/iobroker/node_modules/cheerio/lib/api/traversing.js:562:24)
at Node. (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:492:52)
at initialize.exports.each (/opt/iobroker/node_modules/cheerio/lib/api/traversing.js:562:24)
at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:460:35)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-03 20:19:50.464  - info: stiebel-isg.0 (23999) cleaned everything up...
2021-03-03 20:19:50.487  - info: stiebel-isg.0 (23999) terminating
2021-03-03 20:19:50.490  - info: stiebel-isg.0 (23999) Terminated (NO_ERROR): Without reason
2021-03-03 20:19:51.019  - info: host.raspberrypi instance system.adapter.stiebel-isg.0 terminated with code 0 (NO_ERROR)
2021-03-03 20:19:51.021  - info: host.raspberrypi Restart adapter system.adapter.stiebel-isg.0 because enabled

During the time its running (usually approx. 1 min), I can retrieve data from the ISG. 

Raspberry Pi 3
Linux raspberrypi 5.10.11-v7+
Node.js: v14.13.0
NPM: 6.14.8

Any ideas?

regards
thomas

**Comment by unltdnetworx** [comment]
Sry, for the late answer.

What version of the adapter do you use. If you are using the latest version, you can influence the sites that are scraped. Inside the admin-panel of the adapter you can edit the comma-separated lists.

Maybe you edited one of them? Does all end with a number? Are there any not existing sites in the list?
Just try to set-up a new instance of the adapter without changing anything. Still problems then?

**Comment by tommi296** [comment]
Adapter Version is 1.6.0
Issue was caused by an Update of the ISG SW Version to 12.x. I have reverted ist to 10.2 and Adapter is running again.
