### ISSUE TITLE
Update 1.7.0 --> 1.7.2 Error

### ISSUE THREAD

**Issue by thgonline** [unltdnetworx/ioBroker.stiebel-isg#52]
```


stiebel-isg.0 | 2021-07-28 17:54:32.777 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
stiebel-isg.0 | 2021-07-28 17:54:32.776 | info | terminating
stiebel-isg.0 | 2021-07-28 17:54:32.774 | info | cleaned everything up...
stiebel-isg.0 | 2021-07-28 17:54:32.771 | error | Exception-Code: MODULE_NOT_FOUND: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-07-28 17:54:32.770 | error | Error: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25) at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-07-28 17:54:32.768 | error | uncaught exception: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-07-28 17:54:32.694 | info | starting. Version 1.7.2 in /opt/iobroker/node_modules/iobroker.stiebel-isg, node: v12.22.2, js-controller: 3.3.15


```

**Comment by thgonline** [comment]
1.7.3 now runs without error message

**Comment by unltdnetworx** [comment]
Thx for the feedback
